-- 智能刷题系统数据库说明
--
-- 表结构由后端 SQLAlchemy 模型在应用启动时通过 db.create_all() 自动创建，
-- 默认管理员账号（admin / admin123）同样由应用启动时自动播种。
--
-- 本文件不再直接建表或插入数据：此前手写的 MySQL 建表语句与 ORM 模型存在
-- 定义冲突（如 role 枚举大小写不一致），会导致云端部署时登录/注册报错。
-- 数据库本身由 docker-compose 的 MYSQL_DATABASE=exam_system 创建。
